/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import com.dashboard.Dashboard;
import com.pgsql.Database;
import com.pgsql.JDBCTableAdapter;
import com.vistas.agregar.CU_Cliente;
import com.vistas.agregar.CU_Reservacion;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */
public class Reservacion extends javax.swing.JPanel {

    private Database database;
    
    /**
     * Creates new form Cliente
     * @param database
     */
    public Reservacion(Database database) {
        initComponents();
        this.database = database;
        jButtonObtenerMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonObtener = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Reservación");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable.setGridColor(new java.awt.Color(255, 255, 255));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTable);

        jButtonObtener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonObtener.setText("Obtener");
        jButtonObtener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonObtenerMouseClicked(evt);
            }
        });

        jButtonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jButtonObtener, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(453, 453, 453)))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObtener, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObtenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonObtenerMouseClicked
        final String sql = "SELECT * FROM booking ORDER BY booking_date";
        try (ResultSet rs = database.query(sql)){
            JDBCTableAdapter modelo = new JDBCTableAdapter(rs);
            // modelo.addTableModelListener(new ClientTableListener(database));
            jTable.setModel(modelo);
        } catch (SQLException ex) {
            com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
            jFrameError.setVisible(true);
            throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
        }
    }//GEN-LAST:event_jButtonObtenerMouseClicked

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        Dashboard.setContenido(new CU_Reservacion(database,null));
    }//GEN-LAST:event_jButtonAgregarMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
        int[] filas = jTable.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int eleccion = filas.length == 1 ? 
                JOptionPane.showConfirmDialog(null, "¿Desea eliminar la fila seleccionada?",
                    "Eliminar fila",JOptionPane.YES_NO_CANCEL_OPTION):
                JOptionPane.showConfirmDialog(null, "¿Desea eliminar las filas seleccionadas?",
                    "Eliminar filas",JOptionPane.YES_NO_CANCEL_OPTION);
        if (eleccion != JOptionPane.YES_OPTION) {
            return;
        }
        JDBCTableAdapter modelo = (JDBCTableAdapter) jTable.getModel();
        int filas_modificadas = 0;
        String sql = "DELETE FROM booking WHERE booking_date = ? "
                + "AND number_in_party = ? AND customer_id = ? "
                + "AND table_number = ?;";
        for(int i : filas) {
            try {
                database.empezarTransaccion();
                String fecha = modelo.getValueAt(i, 0).toString();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                LocalDateTime localDateTime = LocalDateTime.parse(fecha, formatter);
                Timestamp timestamp = Timestamp.valueOf(localDateTime);

                PreparedStatement statement = database.con.prepareStatement(sql);
                statement.setTimestamp(1, timestamp);
                statement.setInt(2, Integer.parseInt(modelo.getValueAt(i, 1).toString()));
                statement.setInt(3, Integer.parseInt(modelo.getValueAt(i, 2).toString()));
                statement.setInt(4, Integer.parseInt(modelo.getValueAt(i, 3).toString()));
                filas_modificadas += statement.executeUpdate();
                database.commit();
            }
            catch (SQLException ex) {
                try {
                    database.rollback();
                } catch (SQLException ex1) {
                    com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
                    jFrameError.setVisible(true);
                    throw new RuntimeException("Fallo en hacer rollback", ex);
                }
                com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
                jFrameError.setVisible(true);
                throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
            }
        }
        if (filas_modificadas == 1) {
            JOptionPane.showMessageDialog(null, "Se eliminó " + filas_modificadas + " fila",
                    "Fila eliminada",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Se eliminaron " + filas_modificadas + " filas",
                    "Filas eliminadas",JOptionPane.INFORMATION_MESSAGE);
        }
        jButtonObtenerMouseClicked(null);
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked
        int[] filas = jTable.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para editar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if (filas.length > 1) {
            JOptionPane.showMessageDialog(null, "Selecciona solo una fila para editar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        FilaTabla fila = new FilaTabla(jTable.getModel(),jTable.getSelectedRow());
        Dashboard.setContenido(new CU_Reservacion(database,fila));
    }//GEN-LAST:event_jButtonEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonObtener;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
