/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.procedimientos;

import com.controllers.ComboBoxDB;
import static com.controllers.ComboBoxDB.conseguirID;
import static com.controllers.ComboBoxDB.getPosicionPorValor;
import com.vistas.*;
import com.dashboard.Dashboard;
import com.pgsql.Database;
import com.pgsql.JDBCTableAdapter;
import com.vistas.agregar.CU_Cliente;
import com.vistas.agregar.CU_ObjetoMenu;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Elias
 */
public class ProcedimientoIngredientesObjetoMenu extends javax.swing.JPanel {

    private Database database;
    private FilaTabla fila;
    private int itemID;
    private LinkedHashMap<String, Integer> hashMapItem;
    private final String queryItem = "SELECT menu_item_id, CONCAT(menu_item_description, "
            + "': ', menu_item_price) FROM menu_item ORDER BY menu_item_id;";
    
    /**
     * Creates new form Cliente
     * @param database
     * @param fila
     */
    public ProcedimientoIngredientesObjetoMenu(Database database, FilaTabla fila, Object itemID) {
        initComponents();
        this.database = database;
        this.fila = fila;
        hashMapItem= ComboBoxDB.buildComboBox(this.database, queryItem, jComboBoxItem);
        if (itemID != null) {
            this.itemID = (int) itemID;
            jComboBoxItem.setSelectedIndex(getPosicionPorValor(hashMapItem, this.itemID));
        }
        else if (fila != null) {
            this.itemID = Integer.parseInt(fila.getValue(0).toString());
            jComboBoxItem.setSelectedIndex(getPosicionPorValor(hashMapItem, this.itemID));
        }
        else {
            // Obtiene el primer elemento del hashmap
            this.itemID = hashMapItem.entrySet().iterator().next().getValue();
        }
        jButtonObtenerMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonObtener = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxItem = new javax.swing.JComboBox<>();
        jButtonRetroceder = new javax.swing.JButton();

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Administrar Ingredientes");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable.setGridColor(new java.awt.Color(255, 255, 255));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTable);

        jButtonObtener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonObtener.setText("Obtener");
        jButtonObtener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonObtenerMouseClicked(evt);
            }
        });

        jButtonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Objeto del menú:");

        jComboBoxItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemActionPerformed(evt);
            }
        });

        jButtonRetroceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRetroceder.setText("Retroceder");
        jButtonRetroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRetrocederMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jButtonObtener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBoxItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addGap(134, 134, 134)
                        .addComponent(jButtonRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jButtonRetroceder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObtener, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObtenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonObtenerMouseClicked
        String sql = "SELECT menu_item_id,menu_item_ingredient.ingredient_id,menu_item_ingredient.measurement_id,ingredient_name,item_quantity,measurement_name "
                + "FROM menu_item_ingredient JOIN ingredient ON menu_item_ingredient.ingredient_id = ingredient.ingredient_id "
                + "JOIN measurement ON menu_item_ingredient.measurement_id = measurement.measurement_id "
                + "WHERE menu_item_id = " + itemID + " ORDER BY menu_item_id;";
        try (ResultSet rs = database.query(sql)){
            JDBCTableAdapter modelo = new JDBCTableAdapter(rs);
            // modelo.addTableModelListener(new ClientTableListener(database));
            jTable.setModel(modelo);
            TableColumnModel tcm = jTable.getColumnModel();
            tcm.removeColumn(tcm.getColumn(0));
            tcm.removeColumn(tcm.getColumn(0));
            tcm.removeColumn(tcm.getColumn(0));
        } catch (SQLException ex) {
            com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
            jFrameError.setVisible(true);
            throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
        }
    }//GEN-LAST:event_jButtonObtenerMouseClicked

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        Dashboard.setContenido(new ProcedimientoAgregarIngredienteObjetoMenu(database,itemID,null));
    }//GEN-LAST:event_jButtonAgregarMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
        int[] filas = jTable.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int eleccion = filas.length == 1 ? 
                JOptionPane.showConfirmDialog(null, "¿Desea eliminar la fila seleccionada?",
                    "Eliminar fila",JOptionPane.YES_NO_CANCEL_OPTION):
                JOptionPane.showConfirmDialog(null, "¿Desea eliminar las filas seleccionadas?",
                    "Eliminar filas",JOptionPane.YES_NO_CANCEL_OPTION);
        if (eleccion != JOptionPane.YES_OPTION) {
            return;
        }
        JDBCTableAdapter modelo = (JDBCTableAdapter) jTable.getModel();
        int filas_modificadas = 0;
        String sql = "DELETE FROM menu_item_ingredient WHERE item_quantity = ? "
                + "AND menu_item_id = ? AND ingredient_id = ? "
                + "AND measurement_id = ?;";
        for(int i : filas) {
            try {
                database.empezarTransaccion();
                PreparedStatement statement = database.con.prepareStatement(sql);
                statement.setBigDecimal(1, new BigDecimal(modelo.getValueAt(i, 4).toString()));
                statement.setInt(2, Integer.parseInt(modelo.getValueAt(i, 0).toString()));
                statement.setInt(3, Integer.parseInt(modelo.getValueAt(i, 1).toString()));
                statement.setInt(4, Integer.parseInt(modelo.getValueAt(i, 2).toString()));
                filas_modificadas += statement.executeUpdate();
                database.commit();
            }
            catch (SQLException ex) {
                try {
                    database.rollback();
                } catch (SQLException ex1) {
                    com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
                    jFrameError.setVisible(true);
                    throw new RuntimeException("Fallo en hacer rollback", ex);
                }
                com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
                jFrameError.setVisible(true);
                throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
            }
        }
        if (filas_modificadas == 1) {
            JOptionPane.showMessageDialog(null, "Se eliminó " + filas_modificadas + " fila",
                    "Fila eliminada",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Se eliminaron " + filas_modificadas + " filas",
                    "Filas eliminadas",JOptionPane.INFORMATION_MESSAGE);
        }
        jButtonObtenerMouseClicked(null);
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked
        int[] filas = jTable.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para editar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if (filas.length > 1) {
            JOptionPane.showMessageDialog(null, "Selecciona solo una fila para editar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        FilaTabla fila = new FilaTabla(jTable.getModel(),jTable.getSelectedRow());
        Dashboard.setContenido(new ProcedimientoAgregarIngredienteObjetoMenu(database,itemID,fila));
    }//GEN-LAST:event_jButtonEditarMouseClicked

    private void jComboBoxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemActionPerformed
        if (hashMapItem != null) {
            itemID = conseguirID(hashMapItem, jComboBoxItem);
        }
        jButtonObtenerMouseClicked(null);
    }//GEN-LAST:event_jComboBoxItemActionPerformed

    private void jButtonRetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetrocederMouseClicked
        Dashboard.setContenido(new ObjetoMenu(database));
    }//GEN-LAST:event_jButtonRetrocederMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonObtener;
    private javax.swing.JButton jButtonRetroceder;
    private javax.swing.JComboBox<String> jComboBoxItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
