/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.procedimientos;

import com.controllers.ComboBoxDB;
import static com.controllers.ComboBoxDB.conseguirID;
import static com.controllers.ComboBoxDB.getPosicionPorValor;
import com.vistas.*;
import com.dashboard.Dashboard;
import com.pgsql.Database;
import com.pgsql.JDBCTableAdapter;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Elias
 */
public class ProcedimientoOrdenObjetoMenu extends javax.swing.JPanel {

    private Database database;
    private FilaTabla fila;
    private int ordenID;
    private LinkedHashMap<String, Integer> hashMapOrden;
    private final String queryOrden = "SELECT order_id, "
            + "CONCAT('Orden #', order_id, ' (Mesa ', table_number, ')') FROM \"order\" "
            + "ORDER BY order_id;";
    
    /**
     * Creates new form Cliente
     * @param database
     * @param fila
     * @param ordenID
     */
    public ProcedimientoOrdenObjetoMenu(Database database, FilaTabla fila, Object ordenID) {
        initComponents();
        this.database = database;
        this.fila = fila;
        hashMapOrden= ComboBoxDB.buildComboBox(this.database, queryOrden, jComboBoxOrden);
        if (ordenID != null) {
            this.ordenID = (int) ordenID;
            jComboBoxOrden.setSelectedIndex(getPosicionPorValor(hashMapOrden, this.ordenID));
        }
        else if (fila != null) {
            this.ordenID = Integer.parseInt(fila.getValue(0).toString());
            jComboBoxOrden.setSelectedIndex(getPosicionPorValor(hashMapOrden, this.ordenID));
        }
        else {
            // Obtiene el primer elemento del hashmap
            this.ordenID = hashMapOrden.entrySet().iterator().next().getValue();
        }
        jButtonObtenerMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonObtener = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxOrden = new javax.swing.JComboBox<>();
        jButtonRetroceder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStaff = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTotalCuenta = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Administrar objetos de orden");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable.setGridColor(new java.awt.Color(255, 255, 255));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTable);

        jButtonObtener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonObtener.setText("Obtener");
        jButtonObtener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonObtenerMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Orden:");

        jComboBoxOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrdenActionPerformed(evt);
            }
        });

        jButtonRetroceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRetroceder.setText("Retroceder");
        jButtonRetroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRetrocederMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Atendida por:");

        jTextFieldStaff.setEditable(false);
        jTextFieldStaff.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Total de cuenta:");

        jTextFieldTotalCuenta.setEditable(false);
        jTextFieldTotalCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTotalCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });

        jButtonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(jButtonObtener, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jTextFieldStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(298, 298, 298)))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jTextFieldTotalCuenta)
                                .addContainerGap())))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane))
                        .addContainerGap())
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(392, 392, 392)))
                        .addGap(6, 6, 6))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jButtonRetroceder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTotalCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jTextFieldStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObtener, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrdenActionPerformed
        if (hashMapOrden != null) {
            ordenID = conseguirID(hashMapOrden, jComboBoxOrden);
        }
        jButtonObtenerMouseClicked(null);
    }//GEN-LAST:event_jComboBoxOrdenActionPerformed

    private void jButtonRetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRetrocederMouseClicked
        Dashboard.setContenido(new Orden(database));
    }//GEN-LAST:event_jButtonRetrocederMouseClicked

    private void jButtonObtenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonObtenerMouseClicked
        // JTable
        String sql = "SELECT order_id, order_menu_item.menu_item_id, menu_item_description, "
        + "menu_item_price, order_menu_item_quantity, order_menu_item_coments "
        + "FROM order_menu_item "
        + "JOIN menu_item ON order_menu_item.menu_item_id=menu_item.menu_item_id "
        + "WHERE order_id = " + ordenID + ";";
        try (ResultSet rs = database.query(sql)){
            JDBCTableAdapter modelo = new JDBCTableAdapter(rs);
            // modelo.addTableModelListener(new ClientTableListener(database));
            jTable.setModel(modelo);
            TableColumnModel tcm = jTable.getColumnModel();
            tcm.removeColumn(tcm.getColumn(0));
            tcm.removeColumn(tcm.getColumn(0));
        } catch (SQLException ex) {
            com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
            jFrameError.setVisible(true);
            throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
        }
        // Nombre Staff
        sql = "SELECT CONCAT(staff_first_name, ' ', staff_last_name) "
        + "FROM staff JOIN \"order\" ON \"order\".staff_id=staff.staff_id "
        + "WHERE order_id = " + ordenID + ";";
        try (ResultSet rs = database.query(sql)){
            if (rs.next()) {
                jTextFieldStaff.setText(rs.getString("concat"));
            }
        } catch (SQLException ex) {
            com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
            jFrameError.setVisible(true);
            throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
        }
        // Cuenta total
        sql = "SELECT SUM(menu_item_price * order_menu_item_quantity) "
                + "FROM order_menu_item "
                + "JOIN menu_item ON order_menu_item.menu_item_id = menu_item.menu_item_id "
                + "WHERE order_id = " + ordenID + ";";
        try (ResultSet rs = database.query(sql)){
            if (rs.next()) {
                jTextFieldTotalCuenta.setText(rs.getString("sum"));
            }
        } catch (SQLException ex) {
            com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
            jFrameError.setVisible(true);
            throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
        }
    }//GEN-LAST:event_jButtonObtenerMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked
                int[] filas = jTable.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int eleccion = filas.length == 1 ? 
                JOptionPane.showConfirmDialog(null, "¿Desea eliminar la fila seleccionada?",
                    "Eliminar fila",JOptionPane.YES_NO_CANCEL_OPTION):
                JOptionPane.showConfirmDialog(null, "¿Desea eliminar las filas seleccionadas?",
                    "Eliminar filas",JOptionPane.YES_NO_CANCEL_OPTION);
        if (eleccion != JOptionPane.YES_OPTION) {
            return;
        }
        JDBCTableAdapter modelo = (JDBCTableAdapter) jTable.getModel();
        int filas_modificadas = 0;
        String sql = "DELETE FROM order_menu_item WHERE order_menu_item_quantity = ? "
                + "AND order_menu_item_coments = ? AND order_id = ? "
                + "AND menu_item_id = ?;";
        for(int i : filas) {
            try {
                database.empezarTransaccion();
                PreparedStatement statement = database.con.prepareStatement(sql);
                statement.setInt(1, Integer.parseInt(modelo.getValueAt(i, 4).toString()));
                statement.setString(2, modelo.getValueAt(i, 5).toString());
                statement.setInt(3, Integer.parseInt(modelo.getValueAt(i, 0).toString()));
                statement.setInt(4, Integer.parseInt(modelo.getValueAt(i, 1).toString()));
                filas_modificadas += statement.executeUpdate();
                database.commit();
            }
            catch (SQLException ex) {
                try {
                    database.rollback();
                } catch (SQLException ex1) {
                    com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
                    jFrameError.setVisible(true);
                    throw new RuntimeException("Fallo en hacer rollback", ex);
                }
                com.error.Error jFrameError = new com.error.Error("Error: " + ex.getMessage());
                jFrameError.setVisible(true);
                throw new RuntimeException("Fallo en la consulta ejecutada (" + sql + ")", ex);
            }
        }
        if (filas_modificadas == 1) {
            JOptionPane.showMessageDialog(null, "Se eliminó " + filas_modificadas + " fila",
                    "Fila eliminada",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Se eliminaron " + filas_modificadas + " filas",
                    "Filas eliminadas",JOptionPane.INFORMATION_MESSAGE);
        }
        jButtonObtenerMouseClicked(null);
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        Dashboard.setContenido(new ProcedimientoAgregarOrdenObjetoMenu(database,null,ordenID));
    }//GEN-LAST:event_jButtonAgregarMouseClicked

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked
        int[] filas = jTable.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para editar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if (filas.length > 1) {
            JOptionPane.showMessageDialog(null, "Selecciona solo una fila para editar",
                    "Selección de fila", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        FilaTabla fila = new FilaTabla(jTable.getModel(),jTable.getSelectedRow());
        Dashboard.setContenido(new ProcedimientoAgregarOrdenObjetoMenu(database,fila,ordenID));
    }//GEN-LAST:event_jButtonEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonObtener;
    private javax.swing.JButton jButtonRetroceder;
    private javax.swing.JComboBox<String> jComboBoxOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldStaff;
    private javax.swing.JTextField jTextFieldTotalCuenta;
    // End of variables declaration//GEN-END:variables
}
