/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dashboard;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.pgsql.Database;
import com.vistas.Cliente;
import com.vistas.Principal;
import com.vistas.agregar.C_Table;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author elias
 */
public class Dashboard extends javax.swing.JFrame {
    
    private final Database DATABASE;
    
    /**
     * Creates new form Dashboard
     * @param db
     */
    public Dashboard(Database db) {
        DATABASE = db;
        FlatCyanLightIJTheme.setup();
        initComponents();
        initContent();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanelMenus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonPrincipal = new javax.swing.JButton();
        jButtonClient = new javax.swing.JButton();
        jButtonBooking = new javax.swing.JButton();
        jButtonTable = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonOrderMenuItem = new javax.swing.JButton();
        jButtonBookingMenuItem = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonMenuItemIngredient = new javax.swing.JButton();
        jButtonIngredientType = new javax.swing.JButton();
        jButtonIngrediente = new javax.swing.JButton();
        jButtonIngredientMeasurement = new javax.swing.JButton();
        jButtonMeasurement = new javax.swing.JButton();
        jButtonStaff = new javax.swing.JButton();
        jButtonStaffRole = new javax.swing.JButton();
        jPanelHeader = new javax.swing.JPanel();
        jLabelHeaderTitulo = new javax.swing.JLabel();
        jLabelHeaderIntegrantes = new javax.swing.JLabel();
        jLabelHeaderProfesor = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 900));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(1020, 640));
        fondo.setPreferredSize(new java.awt.Dimension(1020, 640));

        jPanelMenus.setBackground(new java.awt.Color(0, 57, 122));
        jPanelMenus.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RestaurantDB");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N

        jButtonPrincipal.setBackground(new java.awt.Color(0, 131, 219));
        jButtonPrincipal.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrincipal.setText("Cliente");
        jButtonPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonPrincipal.setBorderPainted(false);
        jButtonPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrincipalMouseClicked(evt);
            }
        });

        jButtonClient.setBackground(new java.awt.Color(0, 131, 219));
        jButtonClient.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonClient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClient.setText("Ventana Principal");
        jButtonClient.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonClient.setBorderPainted(false);
        jButtonClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClientMouseClicked(evt);
            }
        });

        jButtonBooking.setBackground(new java.awt.Color(0, 131, 219));
        jButtonBooking.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonBooking.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBooking.setText("Reservación");
        jButtonBooking.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonBooking.setBorderPainted(false);
        jButtonBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBooking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonTable.setBackground(new java.awt.Color(0, 131, 219));
        jButtonTable.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonTable.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTable.setText("Mesa");
        jButtonTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonTable.setBorderPainted(false);
        jButtonTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTableMouseClicked(evt);
            }
        });

        jButtonOrder.setBackground(new java.awt.Color(0, 131, 219));
        jButtonOrder.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOrder.setText("Orden");
        jButtonOrder.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonOrder.setBorderPainted(false);
        jButtonOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonOrderMenuItem.setBackground(new java.awt.Color(0, 131, 219));
        jButtonOrderMenuItem.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonOrderMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOrderMenuItem.setText("Orden de objeto del menú");
        jButtonOrderMenuItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonOrderMenuItem.setBorderPainted(false);
        jButtonOrderMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOrderMenuItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonBookingMenuItem.setBackground(new java.awt.Color(0, 131, 219));
        jButtonBookingMenuItem.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonBookingMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookingMenuItem.setText("Objeto del menú");
        jButtonBookingMenuItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonBookingMenuItem.setBorderPainted(false);
        jButtonBookingMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBookingMenuItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonMenu.setBackground(new java.awt.Color(0, 131, 219));
        jButtonMenu.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMenu.setText("Menú");
        jButtonMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonMenu.setBorderPainted(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonMenuItemIngredient.setBackground(new java.awt.Color(0, 131, 219));
        jButtonMenuItemIngredient.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonMenuItemIngredient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMenuItemIngredient.setText("Ingrediente de objeto del menú");
        jButtonMenuItemIngredient.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonMenuItemIngredient.setBorderPainted(false);
        jButtonMenuItemIngredient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenuItemIngredient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonIngredientType.setBackground(new java.awt.Color(0, 131, 219));
        jButtonIngredientType.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonIngredientType.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngredientType.setText("Tipo de ingrediente");
        jButtonIngredientType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonIngredientType.setBorderPainted(false);
        jButtonIngredientType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngredientType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonIngrediente.setBackground(new java.awt.Color(0, 131, 219));
        jButtonIngrediente.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngrediente.setText("Ingrediente");
        jButtonIngrediente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonIngrediente.setBorderPainted(false);
        jButtonIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonIngredientMeasurement.setBackground(new java.awt.Color(0, 131, 219));
        jButtonIngredientMeasurement.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonIngredientMeasurement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngredientMeasurement.setText("Medición de ingrediente");
        jButtonIngredientMeasurement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonIngredientMeasurement.setBorderPainted(false);
        jButtonIngredientMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngredientMeasurement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonMeasurement.setBackground(new java.awt.Color(0, 131, 219));
        jButtonMeasurement.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonMeasurement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMeasurement.setText("Medición");
        jButtonMeasurement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonMeasurement.setBorderPainted(false);
        jButtonMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMeasurement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonStaff.setBackground(new java.awt.Color(0, 131, 219));
        jButtonStaff.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonStaff.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStaff.setText("Staff");
        jButtonStaff.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonStaff.setBorderPainted(false);
        jButtonStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStaff.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonStaffRole.setBackground(new java.awt.Color(0, 131, 219));
        jButtonStaffRole.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButtonStaffRole.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStaffRole.setText("Rol de staff");
        jButtonStaffRole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonStaffRole.setBorderPainted(false);
        jButtonStaffRole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStaffRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanelMenusLayout = new javax.swing.GroupLayout(jPanelMenus);
        jPanelMenus.setLayout(jPanelMenusLayout);
        jPanelMenusLayout.setHorizontalGroup(
            jPanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenusLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelMenusLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButtonClient, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonTable, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonOrderMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonBookingMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonMenuItemIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonIngredientType, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonIngredientMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonStaffRole, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelMenusLayout.setVerticalGroup(
            jPanelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenusLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButtonClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonOrderMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonBookingMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonMenuItemIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonIngredientType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonIngredientMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonStaffRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelHeader.setBackground(new java.awt.Color(0, 153, 255));

        jLabelHeaderTitulo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelHeaderTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeaderTitulo.setText("Proyecto Final - RestaurantDB");

        jLabelHeaderIntegrantes.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelHeaderIntegrantes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeaderIntegrantes.setText("Por Elías Valdez Miranda y Angel Andrés Santillanes Sanchez");

        jLabelHeaderProfesor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelHeaderProfesor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeaderProfesor.setText("Profesor René Francisco Navarro Hernández - Base de datos I");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHeaderProfesor)
                    .addComponent(jLabelHeaderIntegrantes)
                    .addComponent(jLabelHeaderTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelHeaderTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabelHeaderIntegrantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHeaderProfesor)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(jPanelMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClientMouseClicked
        setContenido(new Principal());
    }//GEN-LAST:event_jButtonClientMouseClicked

    private void jButtonPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrincipalMouseClicked
        setContenido(new Cliente(DATABASE));
    }//GEN-LAST:event_jButtonPrincipalMouseClicked

    private void jButtonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTableMouseClicked
        setContenido(new C_Table());
    }//GEN-LAST:event_jButtonTableMouseClicked

    
    
    private void initContent() {
        setContenido(new Principal());
    }
    
    public static void setContenido(JPanel panel) {
        panel.setSize(611,463);
        panel.setLocation(0,0);
        
        contenido.removeAll();
        contenido.setLayout(new BorderLayout());
        contenido.add(panel, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    // COMENTARIO AQUI
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // COMENTARIO AQUI
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonBookingMenuItem;
    private javax.swing.JButton jButtonClient;
    private javax.swing.JButton jButtonIngredientMeasurement;
    private javax.swing.JButton jButtonIngredientType;
    private javax.swing.JButton jButtonIngrediente;
    private javax.swing.JButton jButtonMeasurement;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMenuItemIngredient;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonOrderMenuItem;
    private javax.swing.JButton jButtonPrincipal;
    private javax.swing.JButton jButtonStaff;
    private javax.swing.JButton jButtonStaffRole;
    private javax.swing.JButton jButtonTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHeaderIntegrantes;
    private javax.swing.JLabel jLabelHeaderProfesor;
    private javax.swing.JLabel jLabelHeaderTitulo;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMenus;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
