/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.error;

/**
 *
 * @author elias
 */
public class Error extends javax.swing.JFrame {
    
    String mensajeError;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Error.class.getName());

    /**
     * Creates new form Error
     * @param mensaje Mensaje del error obtenido
     */
    public Error(String mensaje) {
        mensajeError = mensaje;
        initComponents();
        jTextArea.setText(mensajeError);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        esquina = new javax.swing.JPanel();
        jPanelContinuar = new javax.swing.JPanel();
        jLabelContinuar = new javax.swing.JLabel();
        jPanelCerrarPrograma = new javax.swing.JPanel();
        jLabelCerrarPrograma = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 204, 204));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Ha ocurrido un error!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, -1));

        header.setBackground(new java.awt.Color(255, 204, 204));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        esquina.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout esquinaLayout = new javax.swing.GroupLayout(esquina);
        esquina.setLayout(esquinaLayout);
        esquinaLayout.setHorizontalGroup(
            esquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        esquinaLayout.setVerticalGroup(
            esquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        fondo.add(esquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 40, 30));

        jPanelContinuar.setBackground(new java.awt.Color(0, 153, 255));

        jLabelContinuar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContinuar.setText("Continuar");
        jLabelContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContinuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContinuarLayout = new javax.swing.GroupLayout(jPanelContinuar);
        jPanelContinuar.setLayout(jPanelContinuarLayout);
        jPanelContinuarLayout.setHorizontalGroup(
            jPanelContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanelContinuarLayout.setVerticalGroup(
            jPanelContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondo.add(jPanelContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, 50));

        jPanelCerrarPrograma.setBackground(new java.awt.Color(255, 0, 0));

        jLabelCerrarPrograma.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelCerrarPrograma.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrarPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrarPrograma.setText("Cerrar programa");
        jLabelCerrarPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrarPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarProgramaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCerrarProgramaLayout = new javax.swing.GroupLayout(jPanelCerrarPrograma);
        jPanelCerrarPrograma.setLayout(jPanelCerrarProgramaLayout);
        jPanelCerrarProgramaLayout.setHorizontalGroup(
            jPanelCerrarProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCerrarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanelCerrarProgramaLayout.setVerticalGroup(
            jPanelCerrarProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCerrarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondo.add(jPanelCerrarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 200, 50));

        jTextArea.setEditable(false);
        jTextArea.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setText("Error aquí");
        jTextArea.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 116, 480, 180));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Se ha encontrado la siguiente excepción:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xMouse, yMouse;
    
    private void jLabelCerrarProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarProgramaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCerrarProgramaMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jLabelContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContinuarMouseClicked
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabelContinuarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel esquina;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrarPrograma;
    private javax.swing.JLabel jLabelContinuar;
    private javax.swing.JPanel jPanelCerrarPrograma;
    private javax.swing.JPanel jPanelContinuar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
